name: Build and Release

on:
  push:
    tags:
      - 'v*'   # Run only when you push a tag like v1.0.0

permissions:
  contents: write   # Required for creating releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: src/cli/linux/bitcryptv5.py
          standalone: true

      - name: Debug build output
        run: |
          echo "=== FILE STRUCTURE ==="
          ls -R

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/bitcryptv5.bin
